Traceback (most recent call last):
  File "main.py", line 281, in <module>
    train_acc=train(epoch,net,optimizer)
  File "main.py", line 227, in train
    outputs = net(inputs)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 153, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yonghw/mycode/Opt_GC/cifar/models/resnet.py", line 90, in forward
    out = self.layer1(out)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/container.py", line 100, in forward
    input = module(input)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yonghw/mycode/Opt_GC/cifar/models/resnet.py", line 61, in forward
    out = self.bn3(self.conv3(out))
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/module.py", line 550, in __call__
    result = self.forward(*input, **kwargs)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 349, in forward
    return self._conv_forward(input, self.weight)
  File "/home/yonghw/anaconda3/lib/python3.7/site-packages/torch/nn/modules/conv.py", line 346, in _conv_forward
    self.padding, self.dilation, self.groups)
RuntimeError: CUDA out of memory. Tried to allocate 128.00 MiB (GPU 0; 15.90 GiB total capacity; 1.06 GiB already allocated; 31.38 MiB free; 1.23 GiB reserved in total by PyTorch)
Terminated
